server:
  port: 8080


mybatis-plus:
  global-config:
    db-config:
      id-type: assign_id
spring:
  application:
    name: LLM
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/llm
      username: root
      password: 123456

